config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig

from .views import (
    MailingAttemptsListView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingUpdateView,
    MailingView,
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    MessageUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientListView,
    RecipientUpdateView,
    finish_mailing,
    sending_mail,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", MailingView.as_view(), name="main"),
    path("recipients/", cache_page(60)(RecipientListView.as_view()), name="recipient_list"),
    path("recipients/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipients/create/", RecipientCreateView.as_view(), name="recipient_create"),
    path("recipients/<int:pk>/update/", RecipientUpdateView.as_view(), name="recipient_update"),
    path("recipients/<int:pk>/delete/", RecipientDeleteView.as_view(), name="recipient_delete"),
    path("messages/", cache_page(60)(MessageListView.as_view()), name="message_list"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path("messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("mailing/", cache_page(60)(MailingListView.as_view()), name="mailing_list"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing_attempts/", MailingAttemptsListView.as_view(), name="mailing_attempts_list"),
    path("finish_mailing/<int:pk>/", finish_mailing, name="finish_mailing"),
    path("send_mail/<int:pk>/", sending_mail, name="send_mail"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig

from .views import (
    BlockUserView,
    RegisterView,
    UnblockUserView,
    UserDetailView,
    UserForgotPasswordView,
    UserPasswordResetConfirmView,
    UsersListView,
    UserUpdateView,
    email_verification,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path(
        "register/",
        RegisterView.as_view(template_name="register.html"),
        name="register",
    ),
    path("email_confirm/<str:token>/", email_verification, name="email_verification"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path("set-new-password/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("users_list/", cache_page(60)(UsersListView.as_view()), name="users_list"),
    path("users/<int:pk>/block", BlockUserView.as_view(), name="users_block"),
    path("users/<int:pk>/unblock", UnblockUserView.as_view(), name="users_unblock"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="users_detail"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="users_update"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Модель пользователя."""

    username = None
    email = models.EmailField(unique=True, verbose_name="Электронная почта")
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
        blank=True,
        null=True,
        help_text="Введите Ваше имя",
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия",
        blank=True,
        null=True,
        help_text="Введите Вашу фамилию",
    )
    phone_number = models.CharField(
        max_length=35,
        verbose_name="Номер телефона",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    avatar = models.ImageField(
        upload_to="users/avatars",
        verbose_name="Аватар",
        blank=True,
        null=True,
        help_text="Загрузите Ваш аватар",
    )
    country = models.CharField(
        max_length=50,
        verbose_name="Стана проживания",
        blank=True,
        null=True,
        help_text="Введите Вашу страну проживания",
    )
    token = models.CharField(max_length=100, blank=True, null=True, verbose_name="Токен пользователя")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [("can_block_user", "can block user")]

    def __str__(self):
        return f"{self.first_name} {self.last_name}, e-mail: {self.email}, разблокирован: {self.is_active}"


# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, UserCreationForm

from .models import User


class UserRegisterForm(UserCreationForm):
    phone_number = forms.CharField(max_length=15, required=False, help_text="Введите номер телефона")
    country = forms.CharField(max_length=50, required=False, help_text="Укажите Вашу страну проживания")

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "avatar",
            "country",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите адрес электронной почты"}
        )
        self.fields["first_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите Ваше имя"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите Вашу фамилию"})
        self.fields["phone_number"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите номер телефона"}
        )
        self.fields["avatar"].widget.attrs.update({"class": "form-control", "placeholder": "Загрузите Ваш аватар"})
        self.fields["country"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите Вашу страну проживания"}
        )
        self.fields["password1"].widget.attrs.update({"class": "form-control", "placeholder": "Введите пароль"})
        self.fields["password2"].widget.attrs.update({"class": "form-control", "placeholder": "Введите пароль"})

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры.")
        return phone_number


class UserUpdateForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=15, required=False, help_text="Введите номер телефона")
    country = forms.CharField(max_length=50, required=False, help_text="Укажите Вашу страну проживания")

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "phone_number",
            "avatar",
            "country",
        ]

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите адрес электронной почты"}
        )
        self.fields["first_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите Ваше имя"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите Вашу фамилию"})
        self.fields["phone_number"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите номер телефона"}
        )
        self.fields["avatar"].widget.attrs.update({"class": "form-control", "placeholder": "Загрузите Ваш аватар"})
        self.fields["country"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите Вашу страну проживания"}
        )

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры.")
        return phone_number

    def clean_email_address(self):
        email_address = self.cleaned_data.get("email")
        if User.objects.filter(email=email_address).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Этот адрес электронной почты уже зарегистрирован.")
        return email_address


class UserForgotPasswordForm(PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class UserSetNewPasswordForm(SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})

users/views.py
import secrets

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import CreateView, UpdateView

from .forms import UserForgotPasswordForm, UserRegisterForm, UserSetNewPasswordForm, UserUpdateForm
from .models import User


class RegisterView(CreateView):
    """Контроллер рагистрации в сервисе."""

    template_name = "register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email_confirm/{token}/"
        send_mail(
            subject="Активация аккаунта",
            message=f"Для активации вашего аккаунта перейдите по ссылке: {url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    """Контроллер верификации электронной почты."""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()

    return redirect("users:login")


class UserDetailView(DetailView):
    """Контроллер отображения профиля пользователя."""

    model = User
    template_name = "user_detail.html"


class UserUpdateView(UpdateView):
    """Контроллер обновления профиля пользователя."""

    model = User

    form_class = UserUpdateForm
    template_name = "users_form.html"
    success_url = reverse_lazy("mailing:main")


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """Контроллер по сбросу пароля по почте."""

    form_class = UserForgotPasswordForm
    template_name = "user_password_reset.html"
    success_url = reverse_lazy("mailing:main")
    success_message = "Письмо с инструкцией по восстановлению пароля отправлена на ваш email"
    subject_template_name = "email/password_subject_reset_mail.txt"
    email_template_name = "email/password_reset_mail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Запрос на восстановление пароля"
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """Контроллер установки нового пароля."""

    form_class = UserSetNewPasswordForm
    template_name = "user_password_set_new.html"
    success_url = reverse_lazy("mailing:main")
    success_message = "Пароль успешно изменен. Можете авторизоваться на сайте."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Установить новый пароль"
        return context


class UsersListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка пользователей сервиса."""

    model = User
    template_name = "users_list.html"


class BlockUserView(LoginRequiredMixin, View):
    """Контроллер блокировки пользователей сервиса."""

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        if not request.user.has_perm("can_block_user"):
            return HttpResponseForbidden("У вас нет прав на это действие.")

        user.is_active = False
        user.save()
        return redirect("users:users_list")


class UnblockUserView(LoginRequiredMixin, View):
    """Контроллер разблокировки пользователей сервиса."""

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        if not request.user.has_perm("can_block_user"):
            return HttpResponseForbidden("У вас нет прав на это действие.")

        user.is_active = True
        user.save()
        return redirect("users:users_list")


# Create your views here.

users/templates/login.html
{% extends 'mailing/base_template.html' %}

{% block title %}Вход на сайт{% endblock %}

{% block content %}

<div class="container mt-5">

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            Войти
        </button>

    </form>
    <div class="btn-group mt-5">
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'users:password_reset' %}" role="button">Забыл
            пароль</a>

    </div>
</div>


{% endblock %}

users/templates/register.html
{% extends 'mailing/base_template.html' %}

{% block title %}Регистрация на сайте{% endblock %}

{% block content %}

<div class="container mt-5">
    <h2>Регистрация на сайте</h2>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Зарегистрироваться</button>

    </form>
</div>

{% endblock %}

users/templates/user_detail.html
{% extends 'mailing/base_template.html' %}
{% load my_tags %}
{% block title %}Мой профиль{% endblock %}

{% block content %}


<div class="container">


    <img src="{{ object.avatar | media_filter }}">
    <div class="container mt-3">

        <h4 class="my-0 font-weight-normal mt-3">Электронная почта: {{object.email}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Фамилия: {{object.last_name}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Имя: {{object.first_name}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Номер телефона: {{object.phone_number}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Страна: {{object.country}}</h4>

        <div class="d-flex justify-content-between align-items-center mt-3">
            <div class="btn-group">
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'users:users_update' user.pk %}"
                   role="button">Изменить</a>
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:main' %}"
                   role="button">Назад</a>
            </div>
        </div>
    </div>


</div>


{% endblock %}

users/templates/user_password_reset.html
{% extends 'mailing/base_template.html' %}
{% load my_tags %}
{% block title %}Сброс пароля{% endblock %}

{% block content %}


<
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Запрос на восстановление пароля на сайте</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-dark mt-2" type="submit">Восстановить пароль</button>
        </form>
    </div>
</div>


{% endblock %}

users/templates/user_password_set_new.html
{% extends 'mailing/base_template.html' %}

{% block title %}Вход на сайт{% endblock %}

{% block content %}

<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Установить новый пароль</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-dark mt-2" type="submit">Подтвердить</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users_form.html
{% extends 'mailing/base_template.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}


<div class="container">


    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            Сохранить
        </button>
        <a class="btn btn-secondary" href="{% url 'users:users_detail' user.pk %}">Отмена</a>
    </form>


</div>


{% endblock %}

users/templates/users_list.html
{% extends 'mailing/base_template.html' %}

{% block title %}Страница пользователей{% endblock %}

{% block content %}


<div class="container">
    <div class="container mt-3">
        <h1 class="my-0 font-weight-normal text-center">Пользователи сервиса</h1>
    </div>
    {% for user in object_list %}

    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal">Пользователь: {{user}}</h4>
    </div>
    {% if user.is_active %}
    <div class="btn-group mt-3">
        <form action="{% url 'users:users_block' user.pk %}" method="post">
            {% csrf_token %}
            <button class="btn btn-lg btn-block btn-danger" role="button" type="submit">Заблокировать пользователя
            </button>
        </form>
    </div>
    {% else %}
    <div class="btn-group mt-3">
        <form action="{% url 'users:users_unblock' user.pk %}" method="post">
            {% csrf_token %}
            <button class="btn btn-lg btn-block btn-primary" role="button" type="submit">Разблокировать пользователя
            </button>
        </form>
    </div>
    {% endif %}
    {% endfor %}


</div>


{% endblock %}