config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig

from .views import (
    MailingAttemptsListView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingUpdateView,
    MailingView,
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    MessageUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientListView,
    RecipientUpdateView,
    finish_mailing,
    sending_mail,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", MailingView.as_view(), name="main"),
    path("recipients/", cache_page(60)(RecipientListView.as_view()), name="recipient_list"),
    path("recipients/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipients/create/", RecipientCreateView.as_view(), name="recipient_create"),
    path("recipients/<int:pk>/update/", RecipientUpdateView.as_view(), name="recipient_update"),
    path("recipients/<int:pk>/delete/", RecipientDeleteView.as_view(), name="recipient_delete"),
    path("messages/", cache_page(60)(MessageListView.as_view()), name="message_list"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path("messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("mailing/", cache_page(60)(MailingListView.as_view()), name="mailing_list"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing_attempts/", MailingAttemptsListView.as_view(), name="mailing_attempts_list"),
    path("finish_mailing/<int:pk>/", finish_mailing, name="finish_mailing"),
    path("send_mail/<int:pk>/", sending_mail, name="send_mail"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig

from .views import (
    BlockUserView,
    RegisterView,
    UnblockUserView,
    UserDetailView,
    UserForgotPasswordView,
    UserPasswordResetConfirmView,
    UsersListView,
    UserUpdateView,
    email_verification,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path(
        "register/",
        RegisterView.as_view(template_name="register.html"),
        name="register",
    ),
    path("email_confirm/<str:token>/", email_verification, name="email_verification"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path("set-new-password/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("users_list/", cache_page(60)(UsersListView.as_view()), name="users_list"),
    path("users/<int:pk>/block", BlockUserView.as_view(), name="users_block"),
    path("users/<int:pk>/unblock", UnblockUserView.as_view(), name="users_unblock"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="users_detail"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="users_update"),
]

mailing/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Mailing, Message, Recipient


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ("email", "full_name", "comment")

    def __init__(self, *args, **kwargs):
        super(RecipientForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите адрес электронной почты"}
        )
        self.fields["full_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите полное имя"})
        self.fields["comment"].widget.attrs.update({"class": "form-control", "placeholder": "Введите комментарий"})

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if Recipient.objects.filter(email=email).exists():
            raise ValidationError("Такой адрес электронной почты уже существует в БД!")
        return email


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("subject", "text")

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields["subject"].widget.attrs.update({"class": "form-control", "placeholder": "Введите тему сообщения"})
        self.fields["text"].widget.attrs.update({"class": "form-control", "placeholder": "Введите текст сообщения"})


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ("start_at", "end_at", "status", "message", "recipients")

    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields["start_at"].widget.attrs.update({"class": "form-control", "type": "datetime-local"})
        self.fields["end_at"].widget.attrs.update({"class": "form-control", "type": "datetime-local"})
        self.fields["recipients"].widget.attrs.update({"class": "form-control"})
        self.fields["status"].widget.attrs.update({"class": "form-control"})
        self.fields["message"].widget.attrs.update({"class": "form-control"})

mailing/views.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import MailingForm, MessageForm, RecipientForm
from .models import Mailing, Mailing_Attempts, Message, Recipient
from .service import get_mailing_attempts_list, get_mailing_list, get_message_list, get_recipient_list


class MailingView(TemplateView):
    """Контроллер отображения главной страницы с рассылками."""

    models = [Recipient, Mailing]
    template_name = "mailing/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recipients_all"] = Recipient.objects.all()
        context["mailing_all"] = Mailing.objects.all()
        context["mailing_active"] = Mailing.objects.filter(status=Mailing.ACTIVE)
        return context


class RecipientListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка получателей."""

    model = Recipient
    template_name = "mailing/recipient_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_recipient"):
            return get_recipient_list()
        return get_recipient_list().filter(owner=self.request.user)


class RecipientDetailView(LoginRequiredMixin, DetailView):
    """Контроллер отображения подробностей о получателе."""

    model = Recipient
    template_name = "mailing/recipient_detail.html"


class RecipientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания получателя."""

    model = Recipient
    form_class = RecipientForm
    template_name = "mailing/recipient_form.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def form_valid(self, form):
        recipients = form.save()
        user = self.request.user
        recipients.owner = user
        recipients.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер изменения получателя."""

    model = Recipient
    form_class = RecipientForm
    template_name = "mailing/recipient_form.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")

    def get_success_url(self):
        return reverse_lazy("mailing:recipient_detail", kwargs={"pk": self.object.pk})


class RecipientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер контроллер удаления получателя."""

    model = Recipient
    template_name = "mailing/recipient_confirm_delete.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка сообщений."""

    model = Message
    template_name = "mailing/message_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_message"):
            return get_message_list()
        return get_message_list().filter(owner=self.request.user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Контроллер отображения подробностей о сообщении."""

    model = Message
    template_name = "mailing/message_detail.html"


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания сообщения."""

    model = Message
    form_class = MessageForm
    template_name = "mailing/message_form.html"
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер изменения сообщения."""

    model = Message
    form_class = MessageForm
    template_name = "mailing/message_form.html"
    success_url = reverse_lazy("mailing:message_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")

    def get_success_url(self):
        return reverse_lazy("mailing:message_detail", kwargs={"pk": self.object.pk})


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления сообщения."""

    model = Message
    template_name = "mailing/message_confirm_delete.html"
    success_url = reverse_lazy("mailing:message_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка рассылок."""

    model = Mailing
    template_name = "mailing/mailing_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_mailing"):
            return get_mailing_list()
        return get_mailing_list().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing = self.get_queryset()
        context["mailing_created"] = mailing.filter(status=Mailing.CREATED)
        context["mailing_active"] = mailing.filter(status=Mailing.ACTIVE)
        context["mailing_finished"] = mailing.filter(status=Mailing.FINISHED)
        return context


class MailingDetailView(LoginRequiredMixin, DetailView):
    """Контроллер отображения подробностей о рассылке."""

    model = Mailing
    template_name = "mailing/mailing_detail.html"


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания рассылки."""

    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер изменения рассылки."""

    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")

    def get_success_url(self):
        return reverse_lazy("mailing:mailing_detail", kwargs={"pk": self.object.pk})


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления рассылки."""

    model = Mailing
    template_name = "mailing/mailing_confirm_delete.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")


class MailingAttemptsListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка попыток отправки."""

    model = Mailing_Attempts
    template_name = "mailing/mailing_attempts_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_mailing_attempts"):
            return get_mailing_attempts_list()
        return get_mailing_attempts_list().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        attempt = self.get_queryset()
        context["success"] = attempt.filter(attempt_status="успешно").count()
        context["failure"] = attempt.filter(attempt_status="неуспешно").count()
        context["total"] = attempt.count()
        return context


def sending_mail(request, pk):
    """Контроллер отправки рассылок. Принимает pk рассылки,
    отправляет согласно списка рассылки, вносит необходимые данные в БД"""
    mail = Mailing.objects.get(pk=pk)
    email_from = settings.EMAIL_HOST_USER
    attempts_list = []
    subject = mail.message.subject
    message = mail.message.text
    owner = mail.owner
    recipients_list = [recipient.email for recipient in mail.recipients.all()]
    for recipient in recipients_list:
        try:
            send_mail(subject, message, email_from, recipient_list=[recipient])
            if mail.status == Mailing.CREATED:
                mail.status = Mailing.ACTIVE
                mail.start_at = datetime.now()
                mail.save()
            mailing_attempts = Mailing_Attempts(
                attempt_date=datetime.now(),
                attempt_status=Mailing_Attempts.SUCCESS,
                mail_server_response="Email sent successfully",
                mailing=mail,
                owner=owner,
            )
            mailing_attempts.save()
            result = "Sending mail successful"
            attempts_list.append((result, subject, message, recipient))
        except Exception as e:
            if mail.status == Mailing.CREATED:

mailing/templates/mailing/base_template.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title> {% block title %}{% endblock %} </title>

    <!-- Custom styles for this template -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% include 'mailing/nav.html' %}

<main class="container">
    <div class="bg-body-tertiary p-5 rounded">
        {% block content %}{% endblock %}

    </div>
</main>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/finished_mailing_info.html
{% extends 'mailing/base_template.html' %}

{% block title %}Информирование о завершении рассылки{% endblock %}

{% block content %}


<div class="container">

    <div class="container mt-3">
        <h1 class="mb-4">Информировании об окончании рассылки</h1>
        <h4 class="my-0 font-weight-normal mt-3">Завершена рассылка: {{mail.message.subject}}</h4>

    </div>

</div>


{% endblock %}

mailing/templates/mailing/mailing_attempts_list.html
{% extends 'mailing/base_template.html' %}

{% block title %}Страница отчётов о рассылках{% endblock %}

{% block content %}


<div class="container">
    <div class="container mt-3">
        <h1 class="my-0 font-weight-normal text-center">Статистика о рассылках</h1>
    </div>
    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal">Статистика о рассылках: </h4>
        <h4 class="my-0 font-weight-normal">Успешных попыток рассылок: {{success}}</h4>
        <h4 class="my-0 font-weight-normal">Неуспешных попыток рассылок: {{failure}}</h4>
        <h4 class="my-0 font-weight-normal">Всего рассылок: {{total}}</h4>
    </div>
    <div class="container mt-3">
        <h1 class="my-0 font-weight-normal text-center">Отчёты о рассылках</h1>
    </div>

    {% for mailing_attempt in object_list %}


    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal">Рассылка: </h4>
        <h4 class="my-0 font-weight-normal">Статус: {{mailing_attempt.attempt_status}}</h4>
        <h4 class="my-0 font-weight-normal">Ответ сервера: {{mailing_attempt.mail_server_response}}</h4>
        <h4 class="my-0 font-weight-normal">Дата рассылки: {{mailing_attempt.attempt_date}}</h4>
        <h4 class="my-0 font-weight-normal">Рассылка: {{mailing_attempt.mailing}}</h4>
        <div class="d-flex justify-content-between align-items-center">

        </div>
    </div>

    {% endfor %}


</div>


{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base_template.html' %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}


<div class="container">

    <div class="container mt-3">
        <h1 class="mb-4">Удаление рассылки</h1>
        <p>Вы уверены, что хотите удалить рассылку "{{mailing}}" из базы данных?</p>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a class="btn btn-secondary" href="{% url 'mailing:mailing_list' %}">Отмена</a>
        </form>

    </div>

</div>


{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base_template.html' %}

{% block title %}Подробнее о рассылки{% endblock %}

{% block content %}


<div class="container">


    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal mt-3">Рассылка:</h4>
        <h4 class="my-0 font-weight-normal mt-3">Время первой отправки: {{mailing.start_at}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Время окончания отправки: {{mailing.end_at}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Статус рассылки: {{mailing.status}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Тема сообщения: {{mailing.message}}</h4>

        <div class="d-flex justify-content-between align-items-center mt-3">
            <div class="btn-group">
                {% if mailing.owner == user %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:mailing_delete' mailing.pk %}"
                   role="button">Удалить</a>
                {% endif %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:mailing_list' %}"
                   role="button">Назад</a>
            </div>
        </div>
    </div>


</div>


{% endblock %}

mailing/templates/mailing/main.html
{% extends 'mailing/base_template.html' %}

{% block title %}Главная страница {% endblock %}

{% block content %}


<div class="container">


    <div class="container mt-3">
        <h1 class="my-0 font-weight-normal text-center">Общая информация по рассылкам</h1>
        <h4 class="my-0 font-weight-normal mt-3">Количество всех рассылок: {{mailing_all|length}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Количество активных рассылок: {{mailing_active|length}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Количество уникальных получателей: {{recipients_all|length}}</h4>

    </div>
</div>


{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base_template.html' %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}


<div class="container">

    <div class="container mt-3">
        <h1 class="mb-4">Удаление сообщения</h1>
        <p>Вы уверены, что хотите удалить сообщение "{{message}}" из базы данных?</p>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a class="btn btn-secondary" href="{% url 'mailing:message_list' %}">Отмена</a>
        </form>

    </div>

</div>


{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base_template.html' %}

{% block title %}Подробнее о сообщении{% endblock %}

{% block content %}


<div class="container">


    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal mt-3">Сообщение:</h4>
        <h4 class="my-0 font-weight-normal mt-3">Тема сообщения: {{message.subject}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Текст сообщения: {{message.text}}</h4>

        <div class="d-flex justify-content-between align-items-center mt-3">
            <div class="btn-group">
                {% if message.owner == user %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:message_delete' message.pk %}"
                   role="button">Удалить</a>
                {% endif %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:message_list' %}"
                   role="button">Назад</a>
            </div>
        </div>
    </div>


</div>


{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base_template.html' %}

{% block title %}Создание/изменение сообщений{% endblock %}

{% block content %}


<div class="container">

    <h1 class="mb-4">
        {% if message %}
        Форма изменения сообщения
        {% else %}
        Форма создания сообщения
        {% endif %}
    </h1>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            {% if message %}
            Сохранить
            {% else %}
            Создать
            {% endif %}
        </button>
        <a class="btn btn-secondary" href="{% url 'mailing:message_list' %}">Отмена</a>
    </form>


</div>


{% endblock %}

mailing/templates/mailing/recipient_confirm_delete.html
{% extends 'mailing/base_template.html' %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}


<div class="container">

    <div class="container mt-3">
        <h1 class="mb-4">Удаление получателя</h1>
        <p>Вы уверены, что хотите удалить получателя "{{ recipient}}" из базы данных?</p>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a class="btn btn-secondary" href="{% url 'mailing:recipient_list' %}">Отмена</a>
        </form>

    </div>

</div>


{% endblock %}

mailing/templates/mailing/recipient_detail.html
{% extends 'mailing/base_template.html' %}

{% block title %}Подробнее о получателе{% endblock %}

{% block content %}


<div class="container">


    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal mt-3">Получатель:</h4>
        <h4 class="my-0 font-weight-normal mt-3">Ф.И.О.: {{recipient.full_name}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Адрес почты: {{recipient.email}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Комментарий: {{recipient.comment}}</h4>
        <div class="d-flex justify-content-between align-items-center mt-3">
            <div class="btn-group">
                {% if recipient.owner == user %}
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mailing:recipient_delete' recipient.pk %}" role="button">Удалить</a>
                {% endif %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:recipient_list' %}"
                   role="button">Назад</a>
            </div>
        </div>
    </div>


</div>


{% endblock %}

mailing/templates/mailing/recipient_form.html
{% extends 'mailing/base_template.html' %}

{% block title %}Создание/изменение получателя{% endblock %}

{% block content %}


<div class="container">

    <h1 class="mb-4">
        {% if recipient %}
        Форма изменения получателя
        {% else %}
        Форма создания получателя
        {% endif %}
    </h1>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            {% if recipient %}
            Сохранить
            {% else %}
            Создать
            {% endif %}
        </button>
        <a class="btn btn-secondary" href="{% url 'mailing:recipient_list' %}">Отмена</a>
    </form>


</div>


{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base_template.html' %}

{% block title %}Страница получателей{% endblock %}

{% block content %}


<div class="container">
    <div class="container mt-3">
        <h1 class="my-0 font-weight-normal text-center">Получатели</h1>
    </div>
    {% for recipient in object_list %}


    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal">Получатель: {{recipient}}</h4>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mailing:recipient_detail' recipient.pk %}" role="button">Подробнее</a>
                {% if recipient.owner == user %}
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mailing:recipient_update' recipient.pk %}" role="button">Изменить</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}


</div>
<div class="container">
    <div class="container mt-5">
        <div class="btn-group">
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:recipient_create' %}"
               role="button">Добавить получателя</a>

        </div>
    </div>
</div>


{% endblock %}

mailing/templates/mailing/send_mail_result.html
{% extends 'mailing/base_template.html' %}

{% block title %}Отчёт об отправке рассылки{% endblock %}

{% block content %}


<div class="container">
    <div class="container mt-3">
        <h2 class="my-0 font-weight-normal">Отчёты о рассылках:</h2>
    </div>

    {% for mailing_attempt in attempts_list %}

    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal">Результат рассылки: {{mailing_attempt.0}}</h4>
        <h4 class="my-0 font-weight-normal">Тема рассылки: {{mailing_attempt.1}}</h4>
        <h4 class="my-0 font-weight-normal">Текст рассылки: {{mailing_attempt.2}}</h4>
        <h4 class="my-0 font-weight-normal">Адресаты рассылки: {{mailing_attempt.3}}</h4>

    </div>
    {% endfor %}

</div>


</div>


{% endblock %}